### ISSUE TITLE
Failed to parse NetParameter file

### ISSUE THREAD

**Issue by uefall** [THARUNESHWAR-369/image-colorize#1]
hi, thanks for your nice job.
but when I setup the app and try to make a colorize, this error came out.
it's there some problem with caffe model or prototxt?
```
app.py(exception):  OpenCV(4.5.5) /io/opencv/modules/dnn/src/caffe/caffe_io.cpp:1176: error: (-2:Unspecified error) FAILED: ReadProtoFromBinaryFile(param_file, param). Failed to parse NetParameter file: models/colorization_release_v2.caffemodel in function 'ReadNetParamsFromBinaryFileOrDie'
```

**Comment by uefall** [comment]
my opencv version is

**opencv-python                 4.5.5.64
opencv-python-headless        4.5.5.64**

**Comment by THARUNESHWAR-369** [comment]
create new Environment
Try `pip install requirements.txt`
