### ISSUE TITLE
FAILED: ReadProtoFromBinaryFile(param_file, param). Failed to parse NetParameter file: models/colorization_release_v2.caffemodel in function 'ReadNetParamsFromBinaryFileOrDie'

### ISSUE THREAD

**Issue by Jojanyu15** [THARUNESHWAR-369/image-colorize#2]
Hi, I'm getting this error when I upload a photo and click the start colorization button.
![image](https://user-images.githubusercontent.com/33767841/168130101-9c39dde9-9a0a-4f4d-855d-d5ff25ab03d8.png)

**Comment by THARUNESHWAR-369** [comment]
Use python version 3.10
create a new `virtual environment`
and install the packages `pip install requirements.txt`
